## 科学计算库numpy

### 1. 从文件读取数据

In [110]:
import numpy
from numpy import pi
words = numpy.genfromtxt("words.txt", delimiter=",", dtype=str, skip_header=1)
print(type(words))
#print(help(numpy.genfromtxt))
print(words)
print(words[1,0])
print(words[1,3])


<class 'numpy.ndarray'>
[['b' 'a' 'china' '']
 ['zhan' 'sa' 'lis' 'k']]
zhan
k


### 2. 创建向量和矩阵

In [111]:
vector = numpy.array([5, 10, 15, 20])
matrix = numpy.array([[5, 10 ,15], [3, 4, 5]])
print (vector)
#打印维度
print (vector.shape)

print (matrix)
print (matrix.shape)

[ 5 10 15 20]
(4,)
[[ 5 10 15]
 [ 3  4  5]]
(2, 3)


In [112]:
# 在array中，每个值的类型必须保持一致，否则会类型转换
num = numpy.array([1, 2, 3, 4])
print (num)
num.dtype

[1 2 3 4]


dtype('int64')

### 3. 切片

In [113]:
vector = numpy.array([5, 10, 15, 20])
print(vector[0:3])

[ 5 10 15]


In [114]:
matrix = numpy.array([[5, 10 ,15], [1, 2, 3], [3, 4, 5]])
print(matrix[:,1])
print(matrix[:,0:2])
print(matrix[1:3,1:3])

[10  2  4]
[[ 5 10]
 [ 1  2]
 [ 3  4]]
[[2 3]
 [4 5]]


### 4.判断

In [115]:
vector = numpy.array([1, 2, 3, 4, 5, 6, 7])
equal_to_ten = (vector == 4)
print (equal_to_ten)
#取出那个索引值，和matlab太像了
print(vector[equal_to_ten])

matrix = numpy.array([[5, 10 ,15], [1, 2, 3], [3, 4, 5]])
a = matrix == 15
print (a)

equal_one_and_five = (vector == 1) & (vector == 5)
print (equal_one_and_five)
equal_one_or_five = (vector == 1) | (vector == 5)
print (equal_one_or_five)

[False False False  True False False False]
[4]
[[False False  True]
 [False False False]
 [False False False]]
[False False False False False False False]
[ True False False False  True False False]


### 5.类型转换

In [116]:
vector = numpy.array(["1", "2", "3"])
print (vector.dtype)
print (vector)

vector = vector.astype(float)
print (vector.dtype)
print (vector)


<U1
['1' '2' '3']
float64
[ 1.  2.  3.]


### 6.统计

In [175]:
vector = numpy.array([1, 2, 3, 4, 5, 6, 7])
print(vector.min())
print(vector.mean())
print(vector.sum())
matrix = numpy.array([[5, 10 ,15], [1, 2, 3], [3, 4, 5]])
print(matrix)
print(matrix.max())
print(matrix.sum())
#按行的维度计算
print(matrix.sum(axis=1))
#按列的维度计算
print(matrix.min(axis=0))

1
4.0
28
[[ 5 10 15]
 [ 1  2  3]
 [ 3  4  5]]
15
48
[30  6 12]
[1 2 3]


### 7.造数组和矩阵

In [118]:
print(numpy.arange(15))
a = numpy.arange(15).reshape(3, 5)
print (a)
#打印维度
print(a.shape)
#打印维度的数量
print(a.ndim)
print(a.dtype.name)
#打印总元素数量
print(a.size)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
(3, 5)
2
int64
15


### 8.矩阵操作

In [132]:
#初始化矩阵，零矩阵
print( numpy.zeros((3,4)) )
b = numpy.ones((4,5),dtype=numpy.int32)
print (b)
#造一个范围的数组
c = numpy.arange(10, 30, 5)
print(c)
#随机模块,-1到1之间
numpy.random.random((2,3))

#在一个范围，平均地找一些数
pis = numpy.linspace(0, 2*pi, 100)
print (pis)
numpy.sin(pis)

a = numpy.array([20,30,40,50])
b = numpy.arange(4)
print (a)
print (b)

c = a - b
print (c)

c = c -1
print(c)
#平方操作
print(b**2)
print(a<35)


A = numpy.array([[1,1],[0,1]])
B = numpy.array([[2,0],[3,4]])
print(A)
print(B)
print("--------")
#求内积
print(A*B)

#求矩阵相乘，两种写法
print(A.dot(B))
print(numpy.dot(A,B))

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[10 15 20 25]
[ 0.          0.06346652  0.12693304  0.19039955  0.25386607  0.31733259
  0.38079911  0.44426563  0.50773215  0.57119866  0.63466518  0.6981317
  0.76159822  0.82506474  0.88853126  0.95199777  1.01546429  1.07893081
  1.14239733  1.20586385  1.26933037  1.33279688  1.3962634   1.45972992
  1.52319644  1.58666296  1.65012947  1.71359599  1.77706251  1.84052903
  1.90399555  1.96746207  2.03092858  2.0943951   2.15786162  2.22132814
  2.28479466  2.34826118  2.41172769  2.47519421  2.53866073  2.60212725
  2.66559377  2.72906028  2.7925268   2.85599332  2.91945984  2.98292636
  3.04639288  3.10985939  3.17332591  3.23679243  3.30025895  3.36372547
  3.42719199  3.4906585   3.55412502  3.61759154  3.68105806  3.74452458
  3.8079911   3.87145761  3.93492413  3.99839065  4.06185717  4.12532369
  4.1887902   4.25225672  4.31572324  4.37918976  4.44265628  4.5061228
 

### 9.常用函数

In [154]:
import numpy as np
B = np.arange(3)
print(B)
#e的幂
print(np.exp(B))
#开方
print(np.sqrt(B))
#向下取整
a = np.floor(10*np.random.random((3,4)))
print(a)
#矩阵变为向量
print(a.ravel())
#重新变为指定格式的矩阵
a.shape = (6,2)
print(a)
#转置
print(a.T)


a = np.floor(10*np.random.random((3,4)))
b = np.floor(10*np.random.random((3,4)))
print("----------------")
print(a)
print("----------------")
print(b)
print("----------------")
#按行拼接矩阵
print(np.vstack((a,b)))
# 按列拼接
print(np.hstack((a,b)))

print("----------------")
a = np.floor(10*np.random.random((2,12)))
print(a)
print("----------------")
#按列平均切分几分
print(np.hsplit(a,3))
print("----------------")
#在指定的列切分
print(np.hsplit(a,(3,4)))
print("------vvvvv----------")
a = np.floor(10*np.random.random((12,2)))
print(a)
print("----------------")
#按行平均切分几分
print(np.vsplit(a,3))
print("----------------")
#在指定的行切分
print(np.vsplit(a,(3,4)))

[0 1 2]
[ 1.          2.71828183  7.3890561 ]
[ 0.          1.          1.41421356]
[[ 3.  1.  8.  3.]
 [ 5.  3.  0.  1.]
 [ 0.  0.  2.  4.]]
[ 3.  1.  8.  3.  5.  3.  0.  1.  0.  0.  2.  4.]
[[ 3.  1.]
 [ 8.  3.]
 [ 5.  3.]
 [ 0.  1.]
 [ 0.  0.]
 [ 2.  4.]]
[[ 3.  8.  5.  0.  0.  2.]
 [ 1.  3.  3.  1.  0.  4.]]
----------------
[[ 4.  8.  9.  2.]
 [ 5.  3.  9.  7.]
 [ 8.  2.  6.  4.]]
----------------
[[ 4.  8.  0.  4.]
 [ 3.  0.  6.  5.]
 [ 1.  4.  3.  6.]]
----------------
[[ 4.  8.  9.  2.]
 [ 5.  3.  9.  7.]
 [ 8.  2.  6.  4.]
 [ 4.  8.  0.  4.]
 [ 3.  0.  6.  5.]
 [ 1.  4.  3.  6.]]
[[ 4.  8.  9.  2.  4.  8.  0.  4.]
 [ 5.  3.  9.  7.  3.  0.  6.  5.]
 [ 8.  2.  6.  4.  1.  4.  3.  6.]]
----------------
[[ 4.  5.  1.  2.  2.  7.  9.  4.  4.  3.  1.  9.]
 [ 3.  4.  2.  9.  0.  9.  9.  1.  6.  2.  6.  4.]]
----------------
[array([[ 4.,  5.,  1.,  2.],
       [ 3.,  4.,  2.,  9.]]), array([[ 2.,  7.,  9.,  4.],
       [ 0.,  9.,  9.,  1.]]), array([[ 4.,  3.,  1.,  9.],
       [ 6.

In [170]:
a = np.arange(12)
#两个完全一样
b = a
print(b is a)
b.shape = 3,4
print(b)
print(a.shape)
print(id(a))
print(id(b))
print("----------------")
#浅复制,不推荐使用，虽然不是一样的，但是使用同一个数据
c = a.view()
print(c is a)
c.shape = 2,6
print(a.shape)
c[0,4] = 1234
print(a)
print(id(a))
print(id(c))
print("----------------")
#推荐使用copy函数
d = a.copy()
d is a
d[0,0] = 555
print(d)
print(a)

True
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)
139669295774256
139669295774256
----------------
False
(3, 4)
[[   0    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]
139669295774256
139669295637888
----------------
[[ 555    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]
[[   0    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]


In [180]:
data = np.sin(np.arange(20)).reshape(5,4)
print(data)
#取最大值的索引
ind = data.argmax(axis=0)
print (ind)
data_max = data[ind, range(data.shape[1])]
print(data_max)

[[ 0.          0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155   0.6569866 ]
 [ 0.98935825  0.41211849 -0.54402111 -0.99999021]
 [-0.53657292  0.42016704  0.99060736  0.65028784]
 [-0.28790332 -0.96139749 -0.75098725  0.14987721]]
[2 0 3 1]
[ 0.98935825  0.84147098  0.99060736  0.6569866 ]


In [185]:
a = np.arange(0 ,40 , 10)
print(a)
#行列变为多少倍
b = np.tile(a,(3,5))
print(b)

[ 0 10 20 30]
[[ 0 10 20 30  0 10 20 30  0 10 20 30  0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30  0 10 20 30  0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30  0 10 20 30  0 10 20 30  0 10 20 30]]


In [194]:
a = np.array([[4,3,5],[1,2,1]])
print(a)
print('--------')
#按列排序
b = np.sort(a,axis=0)
print(b)
print('--------')
a.sort(axis=1)
print(a)
print('--------')
print('---nnn-----')
a = np.array([4,3,1,2])
#取排序时候的索引
j = np.argsort(a)
print('--------')
print(j)
print('--------')
print(a[j])

[[4 3 5]
 [1 2 1]]
--------
[[1 2 1]
 [4 3 5]]
--------
[[3 4 5]
 [1 1 2]]
--------
---nnn-----
--------
[2 3 1 0]
--------
[1 2 3 4]
